added example for terraform commands in the shell
binbashar/le-ref-architecture-doc pull request #119
Opened 2022-05-16 18:20 UTC by fgauchat-binbash

## What?
* Added an example box for running TF commands inside shell

## Why?
* Doc was not clear enough for specific use cases (running a TF command not supported by the CLI)
* Adding a specific example of a common issue where we need to use a TF command inside the shell

## References
* There are many TF [commands](https://www.terraform.io/cli/commands) not supported by the CLI (as they are not used on a daily basis). The one used in the example is [force-unlock](https://www.terraform.io/cli/commands/force-unlock).

2022-05-16 21:03 UTC, exequielrafaela requested changes
@fgauchat-binbash the content looks great, only one minor coding syntax review before approving and merging 🚀

2022-05-16 21:03 UTC, exequielrafaela commented on docs/user-guide/leverage-cli/reference/terraform.md
> +
@fgauchat-binbash Fran the content looks great, one thing that call our attention with @angelofenoglio is that there are several extra whitespaces that could be deleted, and the use of a numbered markdown list will be also recommended to follow the standard we use to.

So we'll recommend updating the code as follows please:

```
_Note:_ When `--sso` flag is used, the `--mfa` flag status is ignored.

!!! example "What if I want to run a Terraform command that is not supported by the CLI?"
    One common error you could encounter is `"Error acquiring the state lock"`, where you might need to use `force-unlock`. You can do the following:
        
    1. `leverage terraform shell --sso`
    2. Then from inside the container: `terraform force-unlock LOCK-ID`

---
## `format`
```

CC: @diego-ojeda-binbash

2022-05-17 15:46 UTC, fgauchat-binbash commented on docs/user-guide/leverage-cli/reference/terraform.md
> +
Thanks for the review @exequielrafaela, I've added those changes. Please let me know if there's anything else to change.

2022-05-17 15:56 UTC, exequielrafaela approved these changes
@fgauchat-binbash looks great!!!

Let's remember to add closes https://github.com/binbashar/le-ref-architecture-doc/issues/118 when merging in order to automatically close the associated issue

---
Ref: https://docs.github.com/es/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Linking a pull request to an issue using a keyword**
You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message. The pull request must be on the default branch.

- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev

2022-05-17 15:56 UTC, exequielrafaela commented on docs/user-guide/leverage-cli/reference/terraform.md
> +
@fgauchat-binbash Fran the content looks great, one thing that call our attention with @angelofenoglio is that there are several extra whitespaces that could be deleted, and the use of a numbered markdown list will be also recommended to follow the standard we use to.

So we'll recommend updating the code as follows please:

```
_Note:_ When `--sso` flag is used, the `--mfa` flag status is ignored.

!!! example "What if I want to run a Terraform command that is not supported by the CLI?"
    One common error you could encounter is `"Error acquiring the state lock"`, where you might need to use `force-unlock`. You can do the following:
        
    1. `leverage terraform shell --sso`
    2. Then from inside the container: `terraform force-unlock LOCK-ID`

---
## `format`
```

CC: @diego-ojeda-binbash

2022-05-17 16:24 UTC, exequielrafaela requested changes
@fgauchat-binbash Fran, out of scope but a very opportunity to add a related doc from Opt-

Let's complete the https://leverage.binbash.com.ar/user-guide/ref-architecture-ansible/workflow/ step 6 with the info below 👇🏼 

* Opt-1: $ leverage run apply\["--tags","common"\]
* Opt-2: $ noglob leverage run apply["--tags","common"]
* Opt-3: run $ leverage shell and then ansible-playbook setup.yml --tags common

### Why?
Because we've decided to close this issue (https://github.com/binbashar/leverage/issues/69) and now it makes sense to add the before presented info.

Thanks!

2022-05-18 21:25 UTC, fgauchat-binbash commented on docs/user-guide/leverage-cli/reference/terraform.md
> +
corrected!

2022-05-18 21:27 UTC, fgauchat-binbash commented
> @fgauchat-binbash Fran, out of scope but a very opportunity to add a related doc from Opt-
> 
> Let's complete the https://leverage.binbash.com.ar/user-guide/ref-architecture-ansible/workflow/ step 6 with the info below 👇🏼
> 
> * Opt-1: $ leverage run apply["--tags","common"]
> * Opt-2: $ noglob leverage run apply["--tags","common"]
> * Opt-3: run $ leverage shell and then ansible-playbook setup.yml --tags common
> 
> ### Why?
> Because we've decided to close this issue ([binbashar/leverage#69](https://github.com/binbashar/leverage/issues/69)) and now it makes sense to add the before presented info.
> 
> Thanks!

@exequielrafaela I've added those changes to the ansible doc, with some tweaking of the content. Please check and let me know!

2022-05-18 21:51 UTC, exequielrafaela approved these changes

2022-05-18 21:51 UTC, exequielrafaela commented
@fgauchat-binbash thanks for the updates! Approved 🚀

2022-05-18 21:57 UTC, merged