BBL-105 | Fix: increase size footer social media icons
binbashar/le-ref-architecture-doc pull request #177
Opened 2023-05-03 13:18 UTC by rodriguez-matias

## What?
* Increase size of footer social media icons.
* Resolves the mobile display problem that was detected by Search Console, where buttons were small and too close together.

## Why?
* Improve SEO positioning and resolve mobile display issues.

## References
* Task BBL-105 | Issues fix at binbash.com.ar

## How to check
* Open Google Chrome ->  Developer tools->  Device toolbar icon -> Select  mobile style-> Choose device "iPhone XR"

![image](https://user-images.githubusercontent.com/65817386/235927323-621b94b4-d98b-422d-b5d6-d799388d0d91.png)
![image](https://user-images.githubusercontent.com/65817386/235927382-838a27f6-2504-40f3-8d42-785c9bb006f8.png)
![image](https://user-images.githubusercontent.com/65817386/235927431-9fee0b66-d408-4923-955a-227d4b9915b3.png)

2023-05-03 14:23 UTC, exequielrafaela approved these changes

2023-05-03 14:24 UTC, exequielrafaela requested changes
@rodriguez-matias Matu consider we'll need to sync the same change from `home.html` to `home-es.html` => https://github.com/binbashar/le-ref-architecture-doc/blob/master/material/overrides/home-es.html

2023-05-04 11:33 UTC, rodriguez-matias commented
> @rodriguez-matias Matu consider we'll need to sync the same change from `home.html` to `home-es.html` => https://github.com/binbashar/le-ref-architecture-doc/blob/master/material/overrides/home-es.html

Yes, @exequielrafaela  you're absolutely right. 
It has already been corrected. Ready  for your approval.

2023-05-04 12:57 UTC, exequielrafaela approved these changes

2023-05-04 14:20 UTC, merged