ISSUE-186(doc): clarify SSO layer and project_name config information
binbashar/le-ref-architecture-doc pull request #188
Opened 2023-09-08 13:21 UTC by rodriguez-matias

## What?
Update text:
* SSO layer configuration information about AWS regions.
* How to configurate correctly poyect_name field.

## Why?
* Clarify information about configuration procedure

## References
* 
* closes issue #186, Bug 2 and Bug 4

2023-09-08 13:24 UTC, Franr approved these changes

2023-09-08 20:46 UTC, exequielrafaela requested changes
@rodriguez-matias Matu some small suggestions, in case you find a better version don't hesitate to adjust it as you see fit. Thanks!

2023-09-08 20:46 UTC, exequielrafaela commented on docs/try-leverage/leverage-project-setup.md
> +!!! info "We typically use `us-east-1` and `us-west-2` as our default regions for the majority of our projects. However, please note that these regions may not be the most fitting choice for your spe
@rodriguez-matias Matu I would suggest an small adjustment adding 1ry and 2ry in this sentence. 

> We typically use as 1ry `us-east-1` and 2ry `us-west-2` as our default regions for the majority of our projects

2023-09-08 20:46 UTC, exequielrafaela commented on docs/try-leverage/management-account.md
> +Before working on the SSO layer you have to navigate to the [AWS IAM Identity Center page](https://console.aws.amazon.com/singlesignon/) and enable Single Sign-On (SSO) by clicking on the `Enable` bu
@rodriguez-matias Matu here I would add at the end: "e.g. `us-east-1` for both of them."

**Then:**
Additionally, to ensure a correct integration, make sure to set the primary region for SSO in AWS console to match the primary region of your Leverage project. e.g. `us-east-1` for both of them.

2023-09-13 14:22 UTC, rodriguez-matias commented
@exequielrafaela  Hi, the requested changes are ready.

2023-09-14 13:42 UTC, exequielrafaela approved these changes

2023-09-14 13:44 UTC, merged