Added documentation on how to troubleshoot the case of scaping chars in CLI
binbashar/le-ref-architecture-doc pull request #231
Opened 2024-10-28 19:02 UTC by juanmatias

## What?
* Added documentation on how to escape chars using the command line for resource arrays.

## Why?
* It is not a common case, but it worth to be documented.

## References
N/A

## Important
Please include a screenshot of the pages that you modified to help reviewers. If you are using Chrome, you can follow the instructions below to easily take a full screenshot of the entire page:
1. Right click the page and open the inspector.
2. In the top left of Chrome Inspector you'll see a little phone icon whose tooltip shows "Toggle device emulation".
3. Hit that and a new black bar will appear on the top of the webpage.
4. In the black bar you can pick the dimensions of the screen you want to stimulate -- Since the documentation uses a responsive layout, you'll probably want to set a wide enough value on the width field, e.g. 1024x768, then the height is not as important.
5. In top right of black bar is three dots, in that menu you can do a full page screenshot.

![image](https://github.com/user-attachments/assets/5a82b4f3-611d-4bf6-ad01-ed67254d5c7f)

2024-10-28 19:39 UTC, diego-ojeda-binbash commented on docs/user-guide/troubleshooting/general.md
> +leverage tf import 'aws_organizations_account.accounts[\"accountalias\"]' 99999999999
You can also use `noglob` before the command that needs escaping, like this:
```
noglob leverage tf import 'aws_organizations_account.accounts["accountalias"] 99999999999
```
I think we should document that option as well.

2024-10-28 19:41 UTC, exequielrafaela commented on docs/user-guide/troubleshooting/general.md
> +leverage tf import 'aws_organizations_account.accounts[\"accountalias\"]' 99999999999
This is already documented here https://leverage.binbash.co/user-guide/leverage-cli/reference/terraform/#import

2024-10-30 13:14 UTC, exequielrafaela requested changes
@juanmatias Let's update this PR based on our internal discussion here: https://binbashar.slack.com/archives/GG0PJ78J3/p1730144578139259?thread_ts=1730142394.792759&cid=GG0PJ78J3

When ready let us know and we can approve it and merge it.
Thanks for your collaboration!

2024-12-03 19:20 UTC, juanmatias commented
@exequielrafaela @diego-ojeda-binbash 

Added notes on `noglob` for `import`.

Added notes for `-target` on `plan`, `apply` and `destroy`. Didn´t add notes on noglob because it didn't work on this case for me (neither on `bash` or `zsh`).

2024-12-04 15:27 UTC, exequielrafaela approved these changes

2024-12-04 15:35 UTC, merged