Feature/firewall manager service
binbashar/le-ref-architecture-doc pull request #97
Opened 2021-09-30 03:11 UTC by lgallard

## what
* Add AWS Firewall Manager Service documentation, diagram & icon

## why
* To document AWS Firewall Manager in Leverage Reference Architecture

## references
* [AWS Firewall Manager](https://aws.amazon.com/firewall-manager/)

CC: @diego-ojeda-binbash

2021-09-30 12:02 UTC, diego-ojeda-binbash approved these changes

2021-09-30 16:35 UTC, exequielrafaela requested changes
@lgallard Luis, thanks for your great contribution here! :) Could you please:

* Create the directory `le-ref-architecture-doc/docs/assets/images/diagrams/editable` and also push the source draw.io `aws-fms.html` or `aws-fms.yml` here.

Thanks!

2021-09-30 21:52 UTC, lgallard commented
> @lgallard Luis, thanks for your great contribution here! :) Could you please:
> 
> * Create the directory `le-ref-architecture-doc/docs/assets/images/diagrams/editable` and also push the source draw.io `aws-fms.html` or `aws-fms.yml` here.
> 
> Thanks!

@exequielrafaela done!

2021-10-01 13:03 UTC, exequielrafaela approved these changes

2021-10-05 16:23 UTC, merged